server:
  port: 7001
  servlet:
    context-path: /establishment

spring:
  application:
    name: establishments
  datasource:
    url: jdbc:mysql://localhost:3310/establishment_db
    username: "rootQSS"
    password: "{cipher}f6cdd483e7ddbe25f3d03904951c3417867da48b17e6b94895de28fdc011313a"
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
